[pytest]
# Minimum Pytest version required
minversion = 8.0

# Tell Pytest to treat the root directory as a Python path
pythonpath = .

# Base execution flags
addopts =
    --strict-markers
    --strict-config
    -ra
    --tb=short
    --import-mode=importlib

# Custom test markers
markers =
    ui: Marks tests as Playwright UI tests
    api: Marks tests as HTTP API tests
	e2e: Marks tests that combines API setup teardown with UI test logic
    smoke: Quick sanity check tests
    regression: Full regression test suite

# Test execution paths
testpaths = tests

# Logging Configuration a
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S